// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// };

// export default function HelloLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   );
// }
