import './globals.scss';
import Link from 'next/link';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav className="nav">
          <div>LOGO</div>
          <div className="bikesNav">
            <Link href="/products">All bikes</Link>

            <Link href="/products/1">Aero Pro</Link>
            <Link href="/products/2">Touring Elite</Link>
            <Link href="/products/3">Gravel Pro</Link>
            <Link href="/products/4">Urban Commuter</Link>
          </div>

          <div className="aboutNav">
            <Link href="/about">About</Link>
            <Link href="/cart">Cart (0)</Link>
          </div>
        </nav>
        {children}
        <footer>
          <section className="footerBlock">
            <div></div>
            <div>
              Each Switchblade model is crafted with meticulous attention to
              detail, pushing the boundaries of performance and providing riders
              with a unique cycling experience tailored to their specific needs
              and preferences. Choose the model that matches your riding style
              and embark on your next adventure with confidence.
            </div>
          </section>
        </footer>
      </body>
    </html>
  );
}
